import enum


class UserRole(str, enum.Enum):
    STUDENT = "STUDENT"
    COMPANY_ADMIN = "COMPANY_ADMIN"
    RECRUITER = "RECRUITER"
    HIRING_MANAGER = "HIRING_MANAGER"
    INSTITUTION_ADMIN = "INSTITUTION_ADMIN"
    PLACEMENT_OFFICER = "PLACEMENT_OFFICER"
    FACULTY = "FACULTY"
    DEPARTMENT_HEAD = "DEPARTMENT_HEAD"
    PLATFORM_ADMIN = "PLATFORM_ADMIN"


class Visibility(str, enum.Enum):
    PLATFORM_PUBLIC = "PLATFORM_PUBLIC"
    COMPANY_PRIVATE = "COMPANY_PRIVATE"
    INSTITUTION_PRIVATE = "INSTITUTION_PRIVATE"


class QuestionType(str, enum.Enum):
    MCQ = "MCQ"
    TECHNICAL = "TECHNICAL"
    CODING = "CODING"


class QuestionSourceType(str, enum.Enum):
    COMPANY_PRIVATE = "COMPANY_PRIVATE"
    PLATFORM = "PLATFORM"
    AI_GENERATED = "AI_GENERATED"


class QuestionStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    VALIDATED = "VALIDATED"
    APPROVED = "APPROVED"
    ACTIVE = "ACTIVE"
    REJECTED = "REJECTED"
    RETIRED = "RETIRED"


class RequirementType(str, enum.Enum):
    REQUIRED = "required"
    PREFERRED = "preferred"


class JobStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    SKILLS_EXTRACTED = "SKILLS_EXTRACTED"
    REQUIREMENTS_CONFIRMED = "REQUIREMENTS_CONFIRMED"
    ASSESSMENT_READY = "ASSESSMENT_READY"
    PUBLISHED = "PUBLISHED"
    CLOSED = "CLOSED"


class ProcessingStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ApplicationStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    APPLIED = "APPLIED"
    ASSESSMENT_PENDING = "ASSESSMENT_PENDING"
    ASSESSMENT_COMPLETED = "ASSESSMENT_COMPLETED"
    INTERVIEW_PENDING = "INTERVIEW_PENDING"
    INTERVIEW_COMPLETED = "INTERVIEW_COMPLETED"
    UNDER_REVIEW = "UNDER_REVIEW"
    REJECTED = "REJECTED"
    SHORTLISTED = "SHORTLISTED"
    OFFER = "OFFER"


class EvidenceSourceType(str, enum.Enum):
    RESUME_CLAIM = "RESUME_CLAIM"
    PROJECT = "PROJECT"
    CERTIFICATE = "CERTIFICATE"
    MCQ = "MCQ"
    TECHNICAL_ASSESSMENT = "TECHNICAL_ASSESSMENT"
    CODING = "CODING"
    INTERVIEW = "INTERVIEW"


class SkillRelationType(str, enum.Enum):
    PARENT_OF = "PARENT_OF"
    RELATED_TO = "RELATED_TO"
    PREREQUISITE_OF = "PREREQUISITE_OF"


class AssessmentAttemptStatus(str, enum.Enum):
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    SCORED = "SCORED"
