"""Static seed data for the skill taxonomy.

category -> list of (canonical_name, [aliases])
"""

TAXONOMY: dict[str, list[tuple[str, list[str]]]] = {
    "Programming Languages": [
        ("Python", ["python3", "py"]),
        ("Java", []),
        ("JavaScript", ["js", "ecmascript"]),
        ("TypeScript", ["ts"]),
        ("C", ["c language"]),
        ("C++", ["cpp", "cplusplus"]),
        ("C#", ["csharp", "c sharp"]),
        ("Go", ["golang"]),
        ("Rust", []),
        ("Ruby", []),
        ("PHP", []),
        ("Kotlin", []),
        ("Swift", []),
        ("Scala", []),
        ("R", ["r language"]),
        ("MATLAB", []),
        ("Perl", []),
        ("Dart", []),
        ("Objective-C", []),
        ("Shell Scripting", ["bash", "shell", "bash scripting"]),
        ("PowerShell", []),
        ("Haskell", []),
        ("Elixir", []),
        ("Clojure", []),
        ("Lua", []),
        ("Solidity", []),
        ("SQL", ["structured query language"]),
        ("HTML", ["html5"]),
        ("CSS", ["css3"]),
    ],
    "Frontend": [
        ("React", ["reactjs", "react.js"]),
        ("Redux", []),
        ("Vue.js", ["vue", "vuejs"]),
        ("Angular", ["angularjs"]),
        ("Svelte", []),
        ("Next.js", ["nextjs"]),
        ("Nuxt.js", ["nuxtjs"]),
        ("jQuery", []),
        ("Tailwind CSS", ["tailwindcss", "tailwind"]),
        ("Bootstrap", []),
        ("Sass", ["scss"]),
        ("Webpack", []),
        ("Vite", []),
        ("Responsive Web Design", []),
        ("Web Accessibility", ["a11y"]),
        ("Progressive Web Apps", ["pwa"]),
        ("WebSockets", []),
        ("State Management", []),
        ("Component-Based Architecture", []),
        ("SEO Fundamentals", []),
    ],
    "Backend": [
        ("Node.js", ["nodejs", "node"]),
        ("Express.js", ["express", "expressjs"]),
        ("FastAPI", []),
        ("Django", []),
        ("Django REST Framework", ["drf"]),
        ("Flask", []),
        ("Spring Boot", ["spring"]),
        ("ASP.NET Core", ["aspnet", "asp.net"]),
        ("Ruby on Rails", ["rails"]),
        ("Laravel", []),
        ("NestJS", []),
        ("REST APIs", ["rest", "restful api", "restful apis"]),
        ("GraphQL", []),
        ("gRPC", []),
        ("Microservices Architecture", ["microservices"]),
        ("API Design", []),
        ("Authentication & Authorization", ["auth", "oauth"]),
        ("JWT", ["json web tokens"]),
        ("Message Queues", []),
        ("RabbitMQ", []),
        ("Apache Kafka", ["kafka"]),
        ("Celery", []),
        ("WebSockets Server-Side", []),
        ("Serverless Architecture", ["serverless"]),
        ("Dependency Injection", []),
        ("Event-Driven Architecture", []),
    ],
    "Databases": [
        ("PostgreSQL", ["postgres", "postgre sql", "postgresql db"]),
        ("MySQL", []),
        ("SQLite", []),
        ("MongoDB", ["mongo"]),
        ("Redis", []),
        ("Elasticsearch", []),
        ("Cassandra", ["apache cassandra"]),
        ("DynamoDB", []),
        ("Firebase Firestore", ["firestore"]),
        ("Neo4j", ["graph database"]),
        ("Database Normalization", []),
        ("Database Indexing", []),
        ("Query Optimization", []),
        ("ORM", ["object relational mapping"]),
        ("SQLAlchemy", []),
        ("Prisma", []),
        ("Database Migrations", []),
        ("Data Warehousing", []),
        ("ETL Pipelines", ["etl"]),
        ("Vector Databases", []),
    ],
    "Cloud & DevOps": [
        ("AWS", ["amazon web services"]),
        ("Azure", ["microsoft azure"]),
        ("Google Cloud Platform", ["gcp"]),
        ("Docker", []),
        ("Kubernetes", ["k8s"]),
        ("Terraform", []),
        ("Ansible", []),
        ("CI/CD", ["continuous integration", "continuous deployment"]),
        ("Jenkins", []),
        ("GitHub Actions", []),
        ("GitLab CI", []),
        ("Infrastructure as Code", ["iac"]),
        ("Nginx", []),
        ("Load Balancing", []),
        ("Serverless (Lambda)", ["aws lambda"]),
        ("Cloud Cost Optimization", []),
        ("Monitoring & Observability", ["observability"]),
        ("Prometheus", []),
        ("Grafana", []),
        ("Logging (ELK Stack)", ["elk", "elk stack"]),
        ("Site Reliability Engineering", ["sre"]),
        ("Helm", []),
        ("Linux Administration", ["linux"]),
        ("Networking Fundamentals", ["computer networking"]),
        ("DNS", []),
    ],
    "Version Control & Collaboration": [
        ("Git", []),
        ("GitHub", []),
        ("GitLab", []),
        ("Bitbucket", []),
        ("Code Review", []),
        ("Agile Methodology", ["agile", "scrum"]),
        ("Kanban", []),
        ("Jira", []),
        ("Technical Documentation", []),
        ("Pair Programming", []),
    ],
    "Testing & Quality": [
        ("Unit Testing", []),
        ("Integration Testing", []),
        ("End-to-End Testing", ["e2e testing"]),
        ("Test-Driven Development", ["tdd"]),
        ("Jest", []),
        ("PyTest", ["pytest"]),
        ("Selenium", []),
        ("Cypress", []),
        ("Mocking", []),
        ("Load Testing", []),
        ("Postman", []),
        ("API Testing", []),
        ("Static Code Analysis", []),
        ("Code Coverage", []),
    ],
    "Security": [
        ("Application Security", ["appsec"]),
        ("OWASP Top 10", ["owasp"]),
        ("SQL Injection Prevention", []),
        ("Cross-Site Scripting Prevention", ["xss prevention"]),
        ("Cryptography Basics", ["cryptography"]),
        ("Penetration Testing", ["pentesting"]),
        ("Secure Coding Practices", []),
        ("Identity and Access Management", ["iam"]),
        ("Network Security", []),
        ("Security Auditing", []),
    ],
    "Data Science & ML": [
        ("Machine Learning", ["ml"]),
        ("Deep Learning", []),
        ("Natural Language Processing", ["nlp"]),
        ("Computer Vision", []),
        ("Pandas", []),
        ("NumPy", []),
        ("Scikit-learn", ["sklearn"]),
        ("PyTorch", []),
        ("TensorFlow", []),
        ("Keras", []),
        ("Data Visualization", []),
        ("Matplotlib", []),
        ("Statistical Analysis", ["statistics"]),
        ("Feature Engineering", []),
        ("Model Evaluation", []),
        ("Hyperparameter Tuning", []),
        ("A/B Testing", []),
        ("Time Series Analysis", []),
        ("Reinforcement Learning", []),
        ("Large Language Models", ["llm", "llms"]),
        ("Prompt Engineering", []),
        ("Retrieval-Augmented Generation", ["rag"]),
        ("Vector Embeddings", []),
        ("MLOps", []),
        ("Data Cleaning", []),
        ("Data Pipelines", []),
        ("Big Data Processing", []),
        ("Apache Spark", ["spark"]),
        ("Hadoop", []),
        ("Recommendation Systems", []),
    ],
    "Mobile Development": [
        ("Android Development", ["android"]),
        ("iOS Development", ["ios"]),
        ("React Native", []),
        ("Flutter", []),
        ("SwiftUI", []),
        ("Jetpack Compose", []),
        ("Mobile App Architecture", []),
        ("Push Notifications", []),
        ("App Store Deployment", []),
    ],
    "Computer Science Fundamentals": [
        ("Data Structures", []),
        ("Algorithms", []),
        ("System Design", []),
        ("Object-Oriented Programming", ["oop"]),
        ("Functional Programming", []),
        ("Design Patterns", []),
        ("Operating Systems Concepts", ["operating systems"]),
        ("Computer Architecture", []),
        ("Concurrency & Multithreading", ["multithreading", "concurrency"]),
        ("Distributed Systems", []),
        ("Time & Space Complexity", ["big o notation"]),
        ("Recursion", []),
        ("Dynamic Programming", []),
        ("Graph Algorithms", []),
        ("Sorting Algorithms", []),
        ("Compiler Design", []),
        ("Problem Solving", []),
    ],
    "Product & Soft Skills": [
        ("Communication Skills", []),
        ("Team Collaboration", []),
        ("Technical Leadership", []),
        ("Requirements Analysis", []),
        ("Product Thinking", []),
        ("Stakeholder Management", []),
        ("Mentoring", []),
        ("Time Management", []),
        ("Critical Thinking", []),
        ("Presentation Skills", []),
    ],
}
