"""job assessment target questions

Revision ID: 0ac3652ecd0d
Revises: c71fd27084c7
Create Date: 2026-09-29 16:54:43.410658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ac3652ecd0d'
down_revision: Union[str, Sequence[str], None] = 'c71fd27084c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('assessment_target_questions', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'assessment_target_questions')
    # ### end Alembic commands ###
