"""interview templates pool plan timing

Revision ID: 3b272265fe96
Revises: 0ac3652ecd0d
Create Date: 2026-09-29 17:14:44.388127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b272265fe96'
down_revision: Union[str, Sequence[str], None] = '0ac3652ecd0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_templates',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_templates_job_id'), 'interview_templates', ['job_id'], unique=True)
    op.create_table('interview_pool_questions',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_question_id', sa.UUID(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['source_question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['interview_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_pool_questions_content_hash'), 'interview_pool_questions', ['content_hash'], unique=False)
    op.create_index(op.f('ix_interview_pool_questions_skill_id'), 'interview_pool_questions', ['skill_id'], unique=False)
    op.create_index(op.f('ix_interview_pool_questions_template_id'), 'interview_pool_questions', ['template_id'], unique=False)
    op.add_column('interview_turns', sa.Column('timing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('interview_turns', sa.Column('pool_question_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'interview_turns', 'interview_pool_questions', ['pool_question_id'], ['id'])
    op.add_column('interviews', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'plan')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'interview_turns', type_='foreignkey')
    op.drop_column('interview_turns', 'pool_question_id')
    op.drop_column('interview_turns', 'timing')
    op.drop_index(op.f('ix_interview_pool_questions_template_id'), table_name='interview_pool_questions')
    op.drop_index(op.f('ix_interview_pool_questions_skill_id'), table_name='interview_pool_questions')
    op.drop_index(op.f('ix_interview_pool_questions_content_hash'), table_name='interview_pool_questions')
    op.drop_table('interview_pool_questions')
    op.drop_index(op.f('ix_interview_templates_job_id'), table_name='interview_templates')
    op.drop_table('interview_templates')
    # ### end Alembic commands ###
