"""ai_runs provider routing, usage and cost

Revision ID: 3c45d4c6595b
Revises: 8f8373567597
Create Date: 2026-09-27 22:29:04.416388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c45d4c6595b'
down_revision: Union[str, Sequence[str], None] = '8f8373567597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_runs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('ai_runs', sa.Column('fallback_used', sa.Boolean(), nullable=True))
    op.add_column('ai_runs', sa.Column('fallback_reason', sa.Text(), nullable=True))
    op.add_column('ai_runs', sa.Column('tool_call_success', sa.Boolean(), nullable=True))
    op.add_column('ai_runs', sa.Column('input_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_runs', sa.Column('cached_input_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_runs', sa.Column('output_tokens', sa.Integer(), nullable=True))
    op.add_column('ai_runs', sa.Column('estimated_cost_usd', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_runs', 'estimated_cost_usd')
    op.drop_column('ai_runs', 'output_tokens')
    op.drop_column('ai_runs', 'cached_input_tokens')
    op.drop_column('ai_runs', 'input_tokens')
    op.drop_column('ai_runs', 'tool_call_success')
    op.drop_column('ai_runs', 'fallback_reason')
    op.drop_column('ai_runs', 'fallback_used')
    op.drop_column('ai_runs', 'retry_count')
    # ### end Alembic commands ###
