"""proctoring sessions and events

Revision ID: 5560067f8ae1
Revises: a7c1e2d3f4b5
Create Date: 2026-09-29 15:32:53.240793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5560067f8ae1'
down_revision: Union[str, Sequence[str], None] = 'a7c1e2d3f4b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proctoring_sessions',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('assessment_attempt_id', sa.UUID(), nullable=True),
    sa.Column('interview_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('camera_required', sa.Boolean(), nullable=False),
    sa.Column('microphone_required', sa.Boolean(), nullable=False),
    sa.Column('fullscreen_required', sa.Boolean(), nullable=False),
    sa.Column('preflight_status', sa.String(), nullable=False),
    sa.Column('preflight_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('session_status', sa.String(), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_lost', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['assessment_attempt_id'], ['assessment_attempts.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctoring_sessions_application_id'), 'proctoring_sessions', ['application_id'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_assessment_attempt_id'), 'proctoring_sessions', ['assessment_attempt_id'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_interview_id'), 'proctoring_sessions', ['interview_id'], unique=False)
    op.create_index(op.f('ix_proctoring_sessions_student_id'), 'proctoring_sessions', ['student_id'], unique=False)
    op.create_table('proctoring_events',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['proctoring_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proctoring_events_event_type'), 'proctoring_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_proctoring_events_session_id'), 'proctoring_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proctoring_events_session_id'), table_name='proctoring_events')
    op.drop_index(op.f('ix_proctoring_events_event_type'), table_name='proctoring_events')
    op.drop_table('proctoring_events')
    op.drop_index(op.f('ix_proctoring_sessions_student_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_interview_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_assessment_attempt_id'), table_name='proctoring_sessions')
    op.drop_index(op.f('ix_proctoring_sessions_application_id'), table_name='proctoring_sessions')
    op.drop_table('proctoring_sessions')
    # ### end Alembic commands ###
