"""hiring pipeline stages progress and interview domains

Revision ID: 5f840a106764
Revises: 125b018914a3
Create Date: 2026-09-29 22:39:20.348937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5f840a106764'
down_revision: Union[str, Sequence[str], None] = '125b018914a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hiring_stages',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage_type', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=True),
    sa.Column('proctored', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'stage_type', name='uq_hiring_stage_job_type')
    )
    op.create_index(op.f('ix_hiring_stages_job_id'), 'hiring_stages', ['job_id'], unique=False)
    op.create_table('application_stage_progress',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('hiring_stage_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['hiring_stage_id'], ['hiring_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'hiring_stage_id', name='uq_stage_progress_app_stage')
    )
    op.create_index(op.f('ix_application_stage_progress_application_id'), 'application_stage_progress', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_stage_progress_hiring_stage_id'), 'application_stage_progress', ['hiring_stage_id'], unique=False)
    op.add_column('assessments', sa.Column('stage_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_assessments_stage_type'), 'assessments', ['stage_type'], unique=False)
    op.add_column('interview_pool_questions', sa.Column('kind', sa.String(), nullable=True))
    op.add_column('interview_pool_questions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('interview_pool_questions', sa.Column('layer', sa.Integer(), nullable=True))
    op.alter_column('interview_pool_questions', 'skill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('interview_templates', sa.Column('stage_type', sa.String(), server_default='TECHNICAL_INTERVIEW', nullable=False))
    op.drop_index(op.f('ix_interview_templates_job_id'), table_name='interview_templates')
    op.create_index(op.f('ix_interview_templates_job_id'), 'interview_templates', ['job_id'], unique=False)
    op.create_unique_constraint('uq_interview_template_job_stage', 'interview_templates', ['job_id', 'stage_type'])
    op.add_column('interview_turns', sa.Column('category', sa.String(), nullable=True))
    op.add_column('interview_turns', sa.Column('kind', sa.String(), nullable=True))
    op.add_column('interview_turns', sa.Column('layer', sa.Integer(), nullable=True))
    op.alter_column('interview_turns', 'target_skill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('interviews', sa.Column('stage_type', sa.String(), server_default='TECHNICAL_INTERVIEW', nullable=False))
    op.add_column('interviews', sa.Column('hiring_stage_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_interviews_stage_type'), 'interviews', ['stage_type'], unique=False)
    op.create_foreign_key('fk_interviews_hiring_stage', 'interviews', 'hiring_stages', ['hiring_stage_id'], ['id'])
    op.add_column('proctoring_sessions', sa.Column('hiring_stage_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_proctoring_sessions_hiring_stage', 'proctoring_sessions', 'hiring_stages', ['hiring_stage_id'], ['id'])
    op.add_column('questions', sa.Column('domain', sa.String(), server_default='TECHNICAL', nullable=False))
    op.add_column('questions', sa.Column('category', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('sub_category', sa.String(), nullable=True))
    op.alter_column('questions', 'skill_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_questions_domain'), 'questions', ['domain'], unique=False)
    op.execute("UPDATE questions SET domain = 'CODING' WHERE question_type = 'CODING'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_domain'), table_name='questions')
    op.alter_column('questions', 'skill_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('questions', 'sub_category')
    op.drop_column('questions', 'category')
    op.drop_column('questions', 'domain')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_proctoring_sessions_hiring_stage', 'proctoring_sessions', type_='foreignkey')
    op.drop_column('proctoring_sessions', 'hiring_stage_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_interviews_hiring_stage', 'interviews', type_='foreignkey')
    op.drop_index(op.f('ix_interviews_stage_type'), table_name='interviews')
    op.drop_column('interviews', 'hiring_stage_id')
    op.drop_column('interviews', 'stage_type')
    op.alter_column('interview_turns', 'target_skill_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('interview_turns', 'layer')
    op.drop_column('interview_turns', 'kind')
    op.drop_column('interview_turns', 'category')
    op.drop_constraint('uq_interview_template_job_stage', 'interview_templates', type_='unique')
    op.drop_index(op.f('ix_interview_templates_job_id'), table_name='interview_templates')
    op.create_index(op.f('ix_interview_templates_job_id'), 'interview_templates', ['job_id'], unique=True)
    op.drop_column('interview_templates', 'stage_type')
    op.alter_column('interview_pool_questions', 'skill_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('interview_pool_questions', 'layer')
    op.drop_column('interview_pool_questions', 'category')
    op.drop_column('interview_pool_questions', 'kind')
    op.drop_index(op.f('ix_assessments_stage_type'), table_name='assessments')
    op.drop_column('assessments', 'stage_type')
    op.drop_index(op.f('ix_application_stage_progress_hiring_stage_id'), table_name='application_stage_progress')
    op.drop_index(op.f('ix_application_stage_progress_application_id'), table_name='application_stage_progress')
    op.drop_table('application_stage_progress')
    op.drop_index(op.f('ix_hiring_stages_job_id'), table_name='hiring_stages')
    op.drop_table('hiring_stages')
    # ### end Alembic commands ###
