"""job posting details

Revision ID: 6c448e5c7449
Revises: 3b272265fe96
Create Date: 2026-09-29 18:41:22.479974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c448e5c7449'
down_revision: Union[str, Sequence[str], None] = '3b272265fe96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('work_mode', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location_state', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location_country', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_level', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('experience_min_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('experience_max_years', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('number_of_openings', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('application_deadline', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('compensation_currency', sa.String(length=3), nullable=True))
    op.add_column('jobs', sa.Column('compensation_min', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('compensation_max', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('compensation_period', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('compensation_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('internship_duration_value', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('internship_duration_unit', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('conversion_guaranteed', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('jobs', sa.Column('conversion_notes', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('full_time_compensation_min', sa.Numeric(precision=16, scale=2), nullable=True))
    op.add_column('jobs', sa.Column('full_time_compensation_max', sa.Numeric(precision=16, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'full_time_compensation_max')
    op.drop_column('jobs', 'full_time_compensation_min')
    op.drop_column('jobs', 'conversion_notes')
    op.drop_column('jobs', 'conversion_guaranteed')
    op.drop_column('jobs', 'internship_duration_unit')
    op.drop_column('jobs', 'internship_duration_value')
    op.drop_column('jobs', 'compensation_type')
    op.drop_column('jobs', 'compensation_period')
    op.drop_column('jobs', 'compensation_max')
    op.drop_column('jobs', 'compensation_min')
    op.drop_column('jobs', 'compensation_currency')
    op.drop_column('jobs', 'application_deadline')
    op.drop_column('jobs', 'number_of_openings')
    op.drop_column('jobs', 'experience_max_years')
    op.drop_column('jobs', 'experience_min_years')
    op.drop_column('jobs', 'experience_level')
    op.drop_column('jobs', 'location_country')
    op.drop_column('jobs', 'location_state')
    op.drop_column('jobs', 'location_city')
    op.drop_column('jobs', 'work_mode')
    # ### end Alembic commands ###
