"""pass2: knowledge, provenance, idempotency, governance

Revision ID: 8f8373567597
Revises: 8682dd4f3101
Create Date: 2026-09-27 20:56:50.641934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f8373567597'
down_revision: Union[str, Sequence[str], None] = '8682dd4f3101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_uri', sa.String(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('institution_id', sa.UUID(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('skill_ids', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=True),
    sa.Column('document_version', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.Column('last_ingested_at', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_uri', 'organization_id', 'institution_id', name='uq_knowledge_source_uri_tenant', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_knowledge_sources_institution_id'), 'knowledge_sources', ['institution_id'], unique=False)
    op.create_index(op.f('ix_knowledge_sources_organization_id'), 'knowledge_sources', ['organization_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('embedding_model', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_chunk_doc_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.add_column('agent_runs', sa.Column('context_type', sa.String(), nullable=True))
    op.add_column('agent_runs', sa.Column('context_id', sa.UUID(), nullable=True))
    op.add_column('agent_runs', sa.Column('used_fallback', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('agent_runs', sa.Column('started_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_agent_runs_context_id'), 'agent_runs', ['context_id'], unique=False)
    op.add_column('ai_runs', sa.Column('started_at', sa.String(), nullable=True))
    op.add_column('ai_runs', sa.Column('ended_at', sa.String(), nullable=True))
    op.add_column('ai_runs', sa.Column('input_hash', sa.String(), nullable=True))
    op.add_column('ai_runs', sa.Column('output_hash', sa.String(), nullable=True))
    op.add_column('assessments', sa.Column('plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('audit_events', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_audit_events_organization_id'), 'audit_events', ['organization_id'], unique=False)
    op.add_column('interview_turns', sa.Column('answer_source', sa.String(), nullable=True))
    op.add_column('interview_turns', sa.Column('transcript_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('learning_path_steps', sa.Column('resource_ids', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('learning_resources', sa.Column('provider', sa.String(), nullable=True))
    op.add_column('learning_resources', sa.Column('difficulty', sa.String(), nullable=False, server_default='beginner'))
    op.add_column('learning_resources', sa.Column('estimated_duration', sa.String(), nullable=True))
    op.add_column('learning_resources', sa.Column('prerequisites', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('learning_resources', sa.Column('is_free', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('learning_resources', sa.Column('status', sa.String(), nullable=False, server_default='ACTIVE'))
    op.create_unique_constraint('uq_resource_url_skill', 'learning_resources', ['url', 'skill_id'])
    op.add_column('notifications', sa.Column('event_type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('dedupe_key', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'notifications', ['dedupe_key'])
    op.add_column('processing_jobs', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('processing_jobs', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('content_hash', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('questions', sa.Column('generation_key', sa.String(), nullable=True))
    op.add_column('questions', sa.Column('created_by_user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_questions_content_hash'), 'questions', ['content_hash'], unique=False)
    op.create_unique_constraint(None, 'questions', ['generation_key'])
    op.create_foreign_key(None, 'questions', 'users', ['created_by_user_id'], ['id'])
    op.add_column('skill_evidence', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('skill_evidence', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.create_unique_constraint('uq_skill_evidence_idem', 'skill_evidence', ['idempotency_key'])
    op.add_column('skills', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'is_active')
    op.drop_constraint('uq_skill_evidence_idem', 'skill_evidence', type_='unique')
    op.drop_column('skill_evidence', 'is_deleted')
    op.drop_column('skill_evidence', 'idempotency_key')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'questions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'questions', type_='unique')
    op.drop_index(op.f('ix_questions_content_hash'), table_name='questions')
    op.drop_column('questions', 'created_by_user_id')
    op.drop_column('questions', 'generation_key')
    op.drop_column('questions', 'validation_report')
    op.drop_column('questions', 'source_refs')
    op.drop_column('questions', 'content_hash')
    op.drop_column('processing_jobs', 'payload')
    op.drop_column('processing_jobs', 'celery_task_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_column('notifications', 'dedupe_key')
    op.drop_column('notifications', 'event_type')
    op.drop_constraint('uq_resource_url_skill', 'learning_resources', type_='unique')
    op.drop_column('learning_resources', 'status')
    op.drop_column('learning_resources', 'is_free')
    op.drop_column('learning_resources', 'prerequisites')
    op.drop_column('learning_resources', 'estimated_duration')
    op.drop_column('learning_resources', 'difficulty')
    op.drop_column('learning_resources', 'provider')
    op.drop_column('learning_path_steps', 'resource_ids')
    op.drop_column('interview_turns', 'transcript_meta')
    op.drop_column('interview_turns', 'answer_source')
    op.drop_index(op.f('ix_audit_events_organization_id'), table_name='audit_events')
    op.drop_column('audit_events', 'organization_id')
    op.drop_column('assessments', 'plan')
    op.drop_column('ai_runs', 'output_hash')
    op.drop_column('ai_runs', 'input_hash')
    op.drop_column('ai_runs', 'ended_at')
    op.drop_column('ai_runs', 'started_at')
    op.drop_index(op.f('ix_agent_runs_context_id'), table_name='agent_runs')
    op.drop_column('agent_runs', 'started_at')
    op.drop_column('agent_runs', 'used_fallback')
    op.drop_column('agent_runs', 'context_id')
    op.drop_column('agent_runs', 'context_type')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_knowledge_sources_organization_id'), table_name='knowledge_sources')
    op.drop_index(op.f('ix_knowledge_sources_institution_id'), table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
