"""job distribution and institution approval

Revision ID: bdb9ee33fbcf
Revises: dfc3ee82a784
Create Date: 2026-09-29 16:43:09.786323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bdb9ee33fbcf'
down_revision: Union[str, Sequence[str], None] = 'dfc3ee82a784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('distribution_type', sa.String(), server_default='OPEN_MARKET', nullable=False))
    op.add_column('jobs', sa.Column('target_institution_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('institution_approval', sa.String(), server_default='NOT_REQUIRED', nullable=False))
    op.add_column('jobs', sa.Column('approval_note', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('approved_by_user_id', sa.UUID(), nullable=True))
    op.add_column('jobs', sa.Column('eligibility', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_jobs_target_institution_id'), 'jobs', ['target_institution_id'], unique=False)
    op.create_foreign_key(None, 'jobs', 'users', ['approved_by_user_id'], ['id'])
    op.create_foreign_key(None, 'jobs', 'institutions', ['target_institution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_target_institution_id'), table_name='jobs')
    op.drop_column('jobs', 'eligibility')
    op.drop_column('jobs', 'approved_by_user_id')
    op.drop_column('jobs', 'approval_note')
    op.drop_column('jobs', 'institution_approval')
    op.drop_column('jobs', 'target_institution_id')
    op.drop_column('jobs', 'distribution_type')
    # ### end Alembic commands ###
