"""assessment versions timer layout

Revision ID: c71fd27084c7
Revises: bdb9ee33fbcf
Create Date: 2026-09-29 16:47:45.456504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c71fd27084c7'
down_revision: Union[str, Sequence[str], None] = 'bdb9ee33fbcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_versions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('published_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['published_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_versions_assessment_id'), 'assessment_versions', ['assessment_id'], unique=False)
    op.add_column('assessment_answers', sa.Column('marked_for_review', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('assessment_attempts', sa.Column('version_id', sa.UUID(), nullable=True))
    op.add_column('assessment_attempts', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_attempts', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_attempts', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessment_attempts', sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('assessment_attempts', sa.Column('option_orders', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'assessment_attempts', 'assessment_versions', ['version_id'], ['id'])
    op.add_column('assessments', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'config')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'assessment_attempts', type_='foreignkey')
    op.drop_column('assessment_attempts', 'option_orders')
    op.drop_column('assessment_attempts', 'question_order')
    op.drop_column('assessment_attempts', 'submitted_at')
    op.drop_column('assessment_attempts', 'expires_at')
    op.drop_column('assessment_attempts', 'started_at')
    op.drop_column('assessment_attempts', 'version_id')
    op.drop_column('assessment_answers', 'marked_for_review')
    op.drop_index(op.f('ix_assessment_versions_assessment_id'), table_name='assessment_versions')
    op.drop_table('assessment_versions')
    # ### end Alembic commands ###
