"""round qualification thresholds and results

Revision ID: ff25cda85069
Revises: 5f840a106764
Create Date: 2026-09-29 23:42:09.741905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff25cda85069'
down_revision: Union[str, Sequence[str], None] = '5f840a106764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round_results',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('hiring_stage_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_version', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('score_components', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('override_decision', sa.String(), nullable=True),
    sa.Column('override_reason', sa.String(), nullable=True),
    sa.Column('override_by', sa.UUID(), nullable=True),
    sa.Column('override_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_previous', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['hiring_stage_id'], ['hiring_stages.id'], ),
    sa.ForeignKeyConstraint(['override_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id', 'hiring_stage_id', 'evaluation_version', name='uq_round_result_version')
    )
    op.create_index(op.f('ix_round_results_application_id'), 'round_results', ['application_id'], unique=False)
    op.create_index(op.f('ix_round_results_hiring_stage_id'), 'round_results', ['hiring_stage_id'], unique=False)
    op.add_column('hiring_stages', sa.Column('pass_threshold', sa.Float(), nullable=True))
    op.add_column('hiring_stages', sa.Column('auto_qualify', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('hiring_stages', sa.Column('weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hiring_stages', 'weights')
    op.drop_column('hiring_stages', 'auto_qualify')
    op.drop_column('hiring_stages', 'pass_threshold')
    op.drop_index(op.f('ix_round_results_hiring_stage_id'), table_name='round_results')
    op.drop_index(op.f('ix_round_results_application_id'), table_name='round_results')
    op.drop_table('round_results')
    # ### end Alembic commands ###
